### ISSUE TITLE
Deprecated: Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by msjoker** [derhasi/phpExcelReader#1]
Not working in php 5.3

Error:
Deprecated: Assigning the return value of new by reference is deprecated in /home/testeo4/www/admin/includes/phpExcelReader/Excel/reader.php on line 261 The filename ../archivos/importados/ is not readable

**Comment by derhasi** [comment]
msjoker, the library is very old, and I haven't touched it in a while. There sure are better ones out there currently.

Did you get here from feeds_excel Drupal module?

**Comment by msjoker** [comment]
Hi!, no problem.... Solved:

function Spreadsheet_Excel_Reader()
    {
        $t = new OLERead();
    $this->_ole =& $t;
        //$this->_ole =& new OLERead();
        $this->setUTFEncoder('iconv');
    }

Tnx anyway
